### ISSUE TITLE
Revert to application type errors

### ISSUE THREAD

**Issue by aalowlevel** [programatik29/tokio-rusqlite#20]
Hello.
It's always problematic when i want to write async wrappers and i am not interested to work with neither `tokio_rusqlite` type errors nor `rusqlite` type errors:
```rust
    /** Initialization of the program (async) */
    pub async fn init(connection: Arc<tokio_rusqlite::Connection>) -> Result<Init, MyError> {
        connection
            .call(|connection| crate::config::init(connection)) // this wants to return `MyError` as well.
            // But the new version only wants to work with its error type. I don't want to return `tokio_rusqlite::Error`
            .await
    }
```
I just want to work like i used to in `0.3.0`. Just go back to the old style.

**Comment by programatik29** [comment]
Thanks for feedback. The problem is we added `close` support and that requires `call` returning error.

**Comment by aalowlevel** [comment]
~~You might consider a callback for `close` function as well.~~
Well, I don't know. In this way of design, the `call` function forces the app error type to be wrapped into the error of its type .

**Comment by programatik29** [comment]
I'll try to figure out a way.

**Comment by czocher** [comment]
@programatik29 we can provide two interfaces since clearly both have their pros and cons? Maybe hide the `close` method behind a feature flag? What do you think?

**Comment by programatik29** [comment]
> @programatik29 we can provide two interfaces since clearly both have their pros and cons? Maybe hide the `close` method behind a feature flag? What do you think?

Maybe we can just add a panicking call method and solve this. If close is never called, it would never panic. With proper documentation I think this might be a good solution.

**Comment by czocher** [comment]
Sure, any specific name you have in mind?

**Comment by programatik29** [comment]
> Sure, any specific name you have in mind?

@Czocher Naming it `call_unwrap` and documenting panic behavior should be fine.
