### ISSUE TITLE
Export `params!`

### ISSUE THREAD

**Issue by alessandromazza98** [programatik29/tokio-rusqlite#25]
If a call requires more than 16 parameters, you must use `params!` macro which is not exposed in this crate.

It would be very helpful to expose it so that you don't have to add `rusqlite` just for that

**Comment by abs0luty** [comment]
Closed by [`2add3b7`](https://github.com/programatik29/tokio-rusqlite/commit/2add3b7f5804477bae7b48c94a01062bc7806d83) 🥳
