### ISSUE TITLE
Expose Types

### ISSUE THREAD

**Issue by neckaros** [programatik29/tokio-rusqlite#28]
Like for params could it be possible to expose Types?

https://docs.rs/rusqlite/latest/rusqlite/types/

It is necessary to do FromSQL.

In general why not re-pub all?

**Comment by davehorner** [comment]
Are we supposed to not use rusqlite when using tokio-rusqlite?  With it being re-pub all, it feels like I'm doing it wrong if I've got them both?

**Comment by neckaros** [comment]
> Are we supposed to not use rusqlite when using tokio-rusqlite? With it being re-pub all, it feels like I'm doing it wrong if I've got them both?

Main issue is that you will have to synchronize version of rusqlite and tokio-rusqlite.
Exemple for rusqlite 0.31 you need toktio-rusqlite 0.5.1
for rusqlite 0.30 you need toktio-rusqlite 0.5.0...
If i understand correctly (pretty new to rust and crates)
