### ISSUE TITLE
crates.io release

### ISSUE THREAD

**Issue by czocher** [programatik29/tokio-rusqlite#37]
Hello @programatik29, @abs0luty,
Can we get a new official release on crates.io? The last one was in February (7 months ago). Published crates cannot depend on a version from git, which impedes projects using `tokio-rusqlite`.
Of course I understand that you're volunteering your time and expertise to support this project and therefor have no expectations. I, and a lot of people using this project directly or indirectly, are grateful for your work though.

**Comment by programatik29** [comment]
Sure thing. I got some real world stuff to deal with lately. Can't really do much except check/test then release. Perhaps I can find another maintainer in the future.

**Comment by programatik29** [comment]
Done!
