### ISSUE TITLE
Cut a new version and push to crates.io

### ISSUE THREAD

**Issue by stranger-danger-zamu** [programatik29/tokio-rusqlite#5]
Crates.io is still using the original v0.2.0 release (#2 ea696510ad6e5930590f8dcf65cd244eb1a83974) which will conflict with the latest rusqlite version. The latest commit from August (#4 33914f835453bf28cedfd6d94cebfde21a1407b5) which updates Cargo.toml dependencies versions fixes it. This however was never pushed up to crates.io.

**Comment by programatik29** [comment]
This would require a minor version bump which might be fine. But I would like to decide how to deal with conflicting versions first. I am currently leaning toward re-exporting `rusqlite` and exposing its features in this crate.

**Comment by stranger-danger-zamu** [comment]
I'm not sure what the best answer is, but I feel that it wouldn't particularly help in the grand scheme of things. 

There still could be conflicting versions for projects depending on this library even if you re-export rusqlite. For example even if I wasn't depending on rusqlite directly I am still using serde_rusqlite which would cause the same issue. 

On the other hand, if rusqlite was re-exported I wouldn't have noticed this being an issue. If or when I added serde_rusqlite it might've made the figuring out the root cause more difficult like during the early days of tokio. 

Either way you go about it works for me, just adding my two cents.

**Comment by programatik29** [comment]
I will just bump up the version and publish it to keep it simple.
