### ISSUE TITLE
Use `tokio::task::spawn_blocking` instead of `thread::spawn`

### ISSUE THREAD

**Issue by czocher** [programatik29/tokio-rusqlite#9]
Hello @programatik29,
While creating the async implementation for `rusqlite_migration` [we noticed](https://github.com/cljoly/rusqlite_migration/issues/24#issuecomment-1404309519) that this project is using [`thread::spawn`](https://github.com/programatik29/tokio-rusqlite/blob/32a9075676aae9315faf8e2620bfd4fb8524061e/src/lib.rs#L243) instead of the recommended [`tokio::task::spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) .
Can I create a PR to change that or is there some underlying reason for this approach?

**Comment by programatik29** [comment]
Hello,

This library uses `thread::spawn` intentionally. The reason for not using `tokio::task::spawn_blocking` is background thread being possibly long running. Using `spawn_blocking` would possibly take a thread from the pool for too long without returning and this can cause problems in theory.

For more information about this topic, you can take a look at [this article](https://ryhl.io/blog/async-what-is-blocking/).

That said, one case for `spawn_blocking` can be rapidly opening and closing rusqlite connections in that case it can offer performance benefits but I think that is extremely unusual and out of scope for this crate. For long running tasks, `thread::spawn` is the way to go.

**Comment by czocher** [comment]
Thanks @programatik29, that confirms [my suspicions](https://github.com/cljoly/rusqlite_migration/issues/24#issuecomment-1404589154) :D.

**Comment by programatik29** [comment]
You are talking about `tokio::spawn` there, if you block those it is really bad. `spawn_blocking` has a different much larger thread pool. But it is still a thread pool and limited.

**Comment by czocher** [comment]
Yes I realized after @matze gave me their input, that's why I decided to ask you directly :). Thank you for the article, it made everything clear.

**Comment by matze** [comment]
Ah, read that article a while ago but surely forgot about that nice table at the end.
